[package]
name = "frontend"
version = "2.0.0"
edition.workspace = true

[dependencies]
common = { version = "*", path = "../common" }
yew = { version = "0.22", features = ["hydration"] }
yew-router = "0.19"
