[package]
name = "common"
version = "2.0.0"
edition.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
yew = "0.22"
yew-router = "0.19"
strum = "0.26"
strum_macros = "0.26"
gloo-net = "0.6.0"
cruet = "0.15.0"
